// Code generated by goctl. DO NOT EDIT.
// Source: limit.proto

package server

import (
	"context"

	"codeflow/workspace/demo/grpc-limit-demo/internal/logic"
	"codeflow/workspace/demo/grpc-limit-demo/internal/svc"
	"codeflow/workspace/demo/grpc-limit-demo/proto"
)

type LimitServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedLimitServer
}

func NewLimitServer(svcCtx *svc.ServiceContext) *LimitServer {
	return &LimitServer{
		svcCtx: svcCtx,
	}
}

func (s *LimitServer) Ping(ctx context.Context, in *proto.PingReq) (*proto.PingResp, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
